language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - composer install --prefer-source

script:
  - php scripts/phpcs --config-set php_path php
  - phpunit tests/AllTests.php
  - pear package-validate package.xml
  - php scripts/phpcs CodeSniffer.php CodeSniffer --standard=PEAR --report=summary --ignore=*/tests/* -np
